proxy:
    kibana:
        #The base path is configured in kibana "kibanadashboard" hence we have added servlet as
        servlet_url: /thisisproxycontext/*
#        target_url: http://192.168.2.24/
        target_url: http://http-patch-vidhya.1d35.starter-us-east-1.openshiftapps.com/v1
        logging_enabled: true
        # Enable only if basic auth protected for kibana
        is_auth_enabled: true
        #currently the kibana dashboard is configured as basic auth protected username / password is kibanaadmin/kibanaadmin
        basic_auth: Basic a2liYW5hYWRtaW46QUBsYW1AMTIz
server:
    port: 3333

# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false